version: '3.8'

services:
  mysql:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data:/var/lib/mysql
      - ./startup:/startup:rw
      - ./dump:/mnt/dump
      - ./config:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"
    networks:
      - dump_network
    entrypoint: >
      bash -c "
        /startup/dump.sh
      "

networks:
  dump_network:
    driver: bridge

volumes:
  data:
    driver: local
