version: '3.8'

services:
  postgres:
    image: postgres:17-bullseye
    container_name: postgres_db
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d  # Папка с инициализационными скриптами

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/shop_db -user=shop_user -password=shop_password -baselineOnMigrate=true migrate
    volumes:
      - ./scripts/migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local