ALTER TABLE purchase DROP FOREIGN KEY fk_purchase_customer;

ALTER TABLE purchase MODIFY COLUMN id BIGINT AUTO_INCREMENT NOT NULL;

ALTER TABLE customer MODIFY COLUMN id BIGINT AUTO_INCREMENT NOT NULL;

ALTER TABLE purchase MODIFY COLUMN customer_id BIGINT  NOT NULL;

ALTER TABLE purchase ADD CONSTRAINT fk_purchase_customer FOREIGN KEY (customer_id) REFERENCES customer(id);

ALTER TABLE product MODIFY COLUMN price DECIMAL(12, 2) NOT NULL;

ALTER TABLE product ADD COLUMN attributes JSON DEFAULT NULL;

ALTER TABLE purchase ADD COLUMN metadata JSON DEFAULT NULL;

