version: '3'
services:
  mysql-server-1:
    image: mysql/mysql-server:8.0.12
    ports:
      - "3301:3306"
    volumes:
      - ./scripts/load:/var/lib/mysql-files
    env_file:
      - mysql-server.env
    command: ["mysqld",
              "--server_id=1",
              "--binlog_checksum=NONE",
              "--gtid_mode=ON",
              "--enforce_gtid_consistency=ON",
              "--log_bin",
              "--log_slave_updates=ON",
              "--master_info_repository=TABLE",
              "--relay_log_info_repository=TABLE",
              "--transaction_write_set_extraction=XXHASH64",
              "--user=mysql",
              "--skip-host-cache",
              "--skip-name-resolve",
              "--default_authentication_plugin=mysql_native_password"]

  mysql-server-2:
    image: mysql/mysql-server:8.0.12
    command: ["mysqld",
              "--server_id=2",
              "--binlog_checksum=NONE",
              "--gtid_mode=ON",
              "--enforce_gtid_consistency=ON",
              "--log_bin","--log_slave_updates=ON",
              "--master_info_repository=TABLE",
              "--relay_log_info_repository=TABLE",
              "--transaction_write_set_extraction=XXHASH64",
              "--user=mysql",
              "--skip-host-cache",
              "--skip-name-resolve",
              "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
    env_file:
      - mysql-server.env

  mysql-server-3:
    image: mysql/mysql-server:8.0.12
    command: ["mysqld",
              "--server_id=3",
              "--binlog_checksum=NONE",
              "--gtid_mode=ON",
              "--enforce_gtid_consistency=ON",
              "--log_bin",
              "--log_slave_updates=ON",
              "--master_info_repository=TABLE",
              "--relay_log_info_repository=TABLE",
              "--transaction_write_set_extraction=XXHASH64",
              "--user=mysql",
              "--skip-host-cache",
              "--skip-name-resolve",
              "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
    env_file:
      - mysql-server.env

  mysql-shell:
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    env_file:
      - mysql-shell.env
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3

  mysql-router:
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    env_file:
      - mysql-router.env
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
