version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
    driver: bridge
